In [1]:
2 ** 16

65536

In [5]:
2 ** 128

340282366920938463463374607431768211456

In [2]:
import numpy as np

In [3]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [6]:
a = -456
np.uint8(a)

56

In [12]:
arr = [345234, 876362.12, 0, -1000, 99999999]
np.array(arr, dtype=np.float64)

array([ 3.4523400e+05,  8.7636212e+05,  0.0000000e+00, -1.0000000e+03,
        9.9999999e+07])

In [21]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
arr = arr.reshape(30, 2)

In [25]:
arr[:, -1][::-1]

array([20.55, 19.65, 18.75, 17.85, 16.95, 16.05, 15.15, 14.25, 13.35,
       12.45, 11.55, 10.65,  9.75,  8.85,  7.95,  7.05,  6.15,  5.25,
        4.35,  3.45,  2.55,  1.65,  0.75, -0.15, -1.05, -1.95, -2.85,
       -3.75, -4.65, -5.55])

In [26]:
np.arange(2, 17, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [29]:
arr = np.zeros((10, 10))
arr[1::2, ::2] = 1 
arr[1::2, :] #начиная с 1 через 2

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.]])